[prompts.researcher.retrieve_grader]
user = '''
You are a grader assessing relevance of a retrieved document to a user question.
Here is the retrieved document:\n\n{{ document|trim }}\n\n
Here is the user question: {{ question|trim }}
If the document contains keywords related to the user question, grade it as relevant.
It does not need to be a stringent test. The goal is to filter out erroneous retrievals.
Give a binary score 'yes' or 'no' score to indicate whether the document is relevant to the question.
Provide the binary score as a JSON with a single key 'score' and no preamble or explanation.
'''