[tool.poetry]
name = "fedotllm"
version = "0.1.0"
description = "LLM-based prototype for nexgen AutoML"
authors = ["Alexey Lapin <a.lapin03@gmail.com>"]
license = "BSD 3-Clause"
readme = "README.md"
packages = [
    { include = "fedotllm", from = "." }
]

[tool.poetry.urls]
repository = "https://github.com/aimclub/FEDOT.LLM"

[tool.poetry.dependencies]
python = "~3.10.0"
# Fedot
fedot = "^0.7.3.2"
thegolem = "^0.4.0"
giotto-tda = "~0.6.0"
ripser = "~0.6.4"

# Data processing
pandas = "^2.2.3"
tabulate = "^0.9.0"
scikit-learn = "^1.5.2"

# LangChain ecosystem
langchain = "^0.3.10"
langchain-core = "^0.3.22"
langchain-community = "^0.3.10"
langchain-openai = "^0.2.11"
langgraph = "^0.2.56"
langchain-text-splitters = "^0.3.2"
langchain-nomic = "^0.1.4"
langchain-chroma = "^0.1.4"

# Web Interface
streamlit = "^1.40.2"
streamlit-extras = "^0.5.0"
gradio = "^5.8.0"

# Database and Vector Store
nomic = {extras = ["local"], version = "^3.3.3"}
chromadb = "^0.5.23"

# Utilities
typing-extensions = "^4.12.2"
pydantic = "^2.10.3"
asyncio = "^3.4.3"
ipython = "^8.30.0"
graphviz = "^0.20.3"
markdownify = "^0.14.1"
beautifulsoup4 = "^4.12.3"
dynaconf = "^3.2.6"
watchdog = "^6.0.0"
loguru = "^0.7.3"
autoflake = "^2.3.1"
langfuse = "^2.56.0"
requests = "^2.32.3"
tenacity = "^9.0.0"
langchain-ollama = "^0.2.1"



[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"
mypy = "^1.0"
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
