[config]
model="gpt-4o-mini"
base_url="https://models.inference.ai.azure.com"
#base_url="http://0.0.0.0:4000"
output_dir="exec_out"
dataset_dir="_experiments"
result_dir="results"
fix_tries=3
fedot_timeout=60