version: '3.8'
services:
  fedot_llm:
    build:
      dockerfile: docker/dev.Dockerfile
      context: ..
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces/fedot_llm:cached
    depends_on:
      ollama:
        condition: service_healthy
  
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ../scripts/ollama_entry.sh:/root/ollama_entry.sh
      - ..:/code
      - ../ollama/ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: always
    healthcheck:
      test: ["CMD", "ollama", "--version"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    entrypoint: /root/ollama_entry.sh



  #   environment:
  #     MONGO_ROOT_USERNAME: root
  #     MONGO_ROOT_PASSWORD: example123
  #   depends_on:
  #     - mongo   
  # mongo:
  #   image: mongo
  #   restart: unless-stopped
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example123
  #   ports:
  #     - "27017:27017"
  # 
