[config]
model = "github/DeepSeek-V3-0324"
#model = "gpt-4o"
#model = "llama-3.3-70b-versatile"
embeddings = "text-embedding-3-small"
automl = "Fedot"
#automl = "FedotInd"
#base_url = "https://api.groq.com/openai/v1"
#base_url = "https://models.inference.ai.azure.com"
#base_url = "https://api.vsegpt.ru/v1"
fix_tries = 3
fedot_timeout = 180