[prompts.automl.run_generate_fedot_config]
temperature = 0.2
system=""
user='''
You're a machine learning expert.
You are given a machine learning problem.
<problem_reflection>
{reflection}
</problem_reflection>

<dataset-description>
{dataset_description}
</dataset-description>
Your goal is to define the optimal parameters for an automatic machine learning model fitting framework.
Make sure to fully address the problem goals, rules and constraints.
Use default values if not specified.
'''