[prompts.automl.run_problem_reflection]
temperature = 0.2
system=""
user='''
You're a machine learning expert.
You are given a machine learning problem.
<problem_description>
{description}
</problem_description>

<dataset-description>
{dataset_description}
</dataset-description>

Make sure to fully address the problem goals, rules and constraints.
Your goal is to define the optimal arguments for given function.
'''