[prompts.automl.run_fix_solution]
user="""
You're a machine learning expert.
You are given a machine learning problem.
# About Dataset
[Task]
{user_instruction}
[Path to Dataset]
{dataset_path}
[Files]
{files}

A previous Python solution code was generated for the problem:
```python
{code_recent_solution}
```
Output:
<stdout>
{stdout}
</stdout>
Problem trace:
<trace>
{trace}
</trace>

You need to generate a fixed solution code.
- **Concentrate on solving the problem that caused the error**, don't fix others 
- **Write the whole code**
Answer:
```python
"""